DROP TABLE EMPLOYEE, CUSTOMER, RECEIPT,ITEM, INGREDIENT,RECIPE,ORDERS;

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    PASSWORD VARCHAR(25)
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY ,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    PHONE_NUMBER VARCHAR(25),
    REWARDS_POINTS INT
);

CREATE TABLE RECEIPT (
    RECEIPT_ID INT PRIMARY KEY, 
    EMPLOYEE_ID INT, 
    CUSTOMER_ID INT,
    TIP DECIMAL(3,2),
    ORDER_TIME INT, 
    ORDER_DATE DATE,
   
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)

);

CREATE TABLE ITEM(
    ITEM_ID INT PRIMARY KEY,
    ITEM_NAME VARCHAR(50),
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(3,2)
);

CREATE TABLE INGREDIENT(
    INGREDIENT_ID INT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(50),
    QUANTITY DECIMAL(6,2),
    UNIT VARCHAR(5)
);

CREATE TABLE RECIPE(
    RECIPE_ID INT PRIMARY KEY,
    ITEM_ID INT,
    INGREDIENT_ID INT, 
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)

);

CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    RECEIPT_ID INT,
    ITEM_ID INT,
    FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT(RECEIPT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);

\copy CUSTOMER(CUSTOMER_ID, FIRST_NAME,LAST_NAME,PHONE_NUMBER,REWARDS_POINTS) FROM 'csv_data/customer_data.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"', NULL '')
\copy 