
CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    PASSWORD VARCHAR(25)
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID SERIAL PRIMARY KEY ,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    PHONE_NUMBER VARCHAR(11),
    REWARDS_POINTS INT
);

CREATE TABLE RECEIPT (
    RECEIPT_ID INT PRIMARY KEY, 
    CUSTOMER_ID INT,
    EMPLOYEE_ID INT, 
    ORDER_DATE DATE,
    ORDER_TIME TIME, 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)

);

CREATE TABLE ITEM(
    ITEM_ID SERIAL PRIMARY KEY,
    ITEM_NAME VARCHAR(50),
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(5,2)
);

CREATE TABLE INGREDIENT(
    INGREDIENT_ID SERIAL PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(50),
    QUANTITY DECIMAL(6,2),
    UNIT VARCHAR(5),
    PRICE_PER_UNIT DECIMAL(5,2)
);

CREATE TABLE RECIPE(
    RECIPE_ID INT PRIMARY KEY,
    INGREDIENT_ID INT, 
    ITEM_ID INT,
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)

);

CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    RECEIPT_ID INT,
    ITEM_ID INT,
    FOREIGN KEY (RECEIPT_ID) REFERENCES RECEIPT(RECEIPT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
);