SELECT c.FIRST_NAME, c.LAST_NAME, COUNT(r.receipt_id) AS TOTAL_ORDERS 
FROM CUSTOMER C 
JOIN RECEIPT r ON 
c.CUSTOMER_ID = r.CUSTOMER_ID 
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME 
ORDER BY TOTAL_ORDERS DESC;
